controllers/BackController.php
<?php

/*
 * Controlador principal
 *
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use yii\widgets\ActiveForm;

class BackController extends Controller {

    // vamos a controlar las reglas de acceso
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [''],
                'rules' => [
                    [
                        'actions' => ['chores', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null, //con esto preguntamos que el entorno está en modo test
            ],
        ];
    }

    public function init() {
        parent::init();
        $this->layout = "backLayout";
    }

    public function entrar() {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        if (Yii::$app->user->identity->usuario != "admin") {
            return $this->goHome();
        }
    }

    public function actionIndex() {
        $this->entrar();
        return $this->render("index");
    }

    public function actionLogin() {
        // en caso de no estar logueado nos colocamos en la pagina de inicio

        if (!Yii::$app->user->isGuest) {
            return $this->redirect(["back/index"]);
        }

        $model = new LoginForm();
        // en caso de intentar realizar un logueo
        if ($model->load(Yii::$app->request->post()) && $model->admin()) {

            return $this->redirect(["back/index"]);
        }

        // en caso de que el logueo no sea correcto no entramos
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    public function actionLogout() {
        // nos salimos de la sesion
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /* accion para enviar un correo con formulario */

    public function actionContact($id) {
        $model = new ContactForm();
        $usuario=User::findIdentity($id);
        
        if ($model->load(Yii::$app->request->post()) && $model->contact()) {
            Yii::$app->session->setFlash('Email');
            //evitar envio masivo del correo con F5
            return $this->goHome();
        }
        
        $model->name=$usuario->usuario;
        $model->email=$usuario->email;
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }
    

    public function actionRegistrar() {
        $model = new User();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        /* crear el usuario */
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->refresh();
        }

        return $this->render('registro', [
                    'model' => $model,
        ]);
    }

    public function actionAjax() {
        $model = new User();

        /* validar por AJAX */
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        } else {
            return $this->renderAjax('registro', [
                        'model' => $model,
            ]);
        }
    }

    public function actionChema() {
        $this->redirect(['site/index']);
    }

    public function actionFormSubmission() {
        $security = new Security();
        $string = Yii::$app->request->post('string');
        $stringHash = '';
        if (!is_null($string)) {
            $stringHash = $security->generatePasswordHash($string);
        }
        return $this->render('form-submission', [
                    'stringHash' => $stringHash,
        ]);
    }

    public function actionAutoRefresh() {
        return $this->render('auto-refresh', ['time' => date('H:i:s')]);
    }

}

controllers/FrontController.php
<?php

/*
 * Controlador principal
 *
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\User;
use yii\widgets\ActiveForm;

class FrontController extends Controller {

    // vamos a controlar las reglas de acceso
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['contact'],
                'rules' => [
                    [
                        'actions' => ['contact', 'chores', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null, //con esto preguntamos que el entorno está en modo test
            ],
        ];
    }

    public function actionIndex() {
        $this->layout = "frontLayout";
        // cargamos la pagina de inicio
        return $this->render('index');
    }

    public function actionLogin($id = 0) {
        // en caso de no estar logueado nos colocamos en la pagina de inicio
        $this->layout = "frontLayout";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        // en caso de intentar realizar un logueo
        if ($id == 0) {
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                // si es correcto volvemos a la pagina anterior
                return $this->goBack();
            }

            // en caso de que el logueo no sea correcto no entramos
            return $this->renderPartial('login', [
                        'model' => $model,
            ]);
        } else {

            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    public function actionLogout() {
        // nos salimos de la sesion
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact() {
        $this->layout = "frontLayout";
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('Email');
            //evitar envio masivo del correo con F5
            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    public function actionRegistrar() {
        $this->layout = "frontLayout";
        $model = new User();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        /* crear el usuario */
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->goHome();
        }

        return $this->render('registro', [
                    'model' => $model,
        ]);
    }

    public function actionAjax() {
        $model = new User();

        /* validar por AJAX */
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        } else {
            return $this->renderAjax('registro', [
                        'model' => $model,
            ]);
        }
    }

    public function actionChema() {
        $this->redirect(['site/index']);
    }
    
    public function actionConfirm() {
        if (Yii::$app->request->get()) {

            //Obtenemos el valor de los parámetros get
            $id = \yii\helpers\Html::decode($_GET["id"]);
            $authKey = \yii\helpers\Html::decode($_GET["authKey"]);

            if ((int) $id) {
                //Realizamos la consulta para obtener el registro
                $model = User::find()
                        ->where("id=:id", [":id" => $id])
                        ->andWhere("authKey=:authKey", [":authKey" => $authKey]);
                
                //Si el registro existe
                if ($model->count() == 1) {
                    $activar = User::findOne($id);
                    $activar->active = 1;
//                    $activar->scenario="actualizar";
                    
                    if ($activar->save(false)) {
                        echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; " . \yii\helpers\Url::to(["index"]) . "'>";
                    } else {
                        echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; " . \yii\helpers\Url::to(["index"]) . "'>";
                    }
                } else { //Si no existe redireccionamos a login
                    return $this->redirect(["index"]);
                }
            } else { //Si id no es un número entero redireccionamos a login
                return $this->redirect(["index"]);
            }
        }
    }

}

views/layouts/backLayout.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <link rel="shortcut icon" href="<?= Yii::getAlias('@web') ?>/imgs/admins.ico" type="image/x-icon" />
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <?=
        $this->registerCssFile("@web/css/mio.css", [
            'depends' => [\yii\bootstrap\BootstrapAsset::className()]
        ]);
        ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => 'Control Panel Task Manager',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);

            if (Yii::$app->user->isGuest) {
                echo Nav::widget([
                    'options' => ['class' => 'navbar-nav navbar-right'],
                    'encodeLabels' => false,
                    'items' => [
                        ['label' => '<span class="glyphicon glyphicon-ok"></span> Login', 'url' => ['/back/login'], 'linkOptions' => ["class" => "modalLogin"]]
                    ],
                ]);
                NavBar::end();
            } else {
                echo Nav::widget([
                    'options' => ['class' => 'navbar-nav navbar-right'],
                    'encodeLabels' => false,
                    'items' => [
                        ['label' => '<span class="glyphicon glyphicon-user"></span> Users', 'url' => ['/user']],
                        ['label' => '<span class="glyphicon glyphicon-tags"></span> Chores', 'url' => ['/chores']],
                        ['label' => '<span class="glyphicon glyphicon-bookmark"></span> Categories', 'url' => ['/categories']],
                        (
                        '<li>'
                        . Html::beginForm(['/back/logout'], 'post')
                        . Html::submitButton(
                                '<span class="glyphicon glyphicon-off"></span> Logout (' . Yii::$app->user->identity->usuario . ')', ['class' => 'btn btn-link logout']
                        )
                        . Html::endForm()
                        . '</li>'
                        )
                    ],
                ]);
                NavBar::end();
            }
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container" >
                <p class="pull-right">Jose María Cagigas Céspedes - Task Manager 2018</p>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/frontLayout.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <link rel="shortcut icon" href="<?= Yii::getAlias('@web') ?>/imgs/users.ico" type="image/x-icon" />
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <?=
        $this->registerCssFile("@web/css/mio.css", [
            'depends' => [\yii\bootstrap\BootstrapAsset::className()]
        ]);
        ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => Yii::$app->name,
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);

            if (Yii::$app->user->isGuest) {
                echo Nav::widget([
                    'options' => ['class' => 'navbar-nav navbar-right'],
                    'encodeLabels' => false,
                    'items' => [
                        ['label' => '<span class="glyphicon glyphicon-ok"></span> Login', 'url' => ['/front/login'], 'linkOptions' => ["class" => "modalLogin"]]
                    ],
                ]);
                NavBar::end();
            } else {
                echo Nav::widget([
                    'options' => ['class' => 'navbar-nav navbar-right'],
                    'encodeLabels' => false,
                    'items' => [
                        ['label' => '<span class="glyphicon glyphicon-tags"></span> Chores', 'url' => ['/frontchores']],
                        ['label' => '<span class="glyphicon glyphicon-envelope"></span> Contact', 'url' => ['/front/contact']],
                        (
                        '<li>'
                        . Html::beginForm(['/back/logout'], 'post')
                        . Html::submitButton(
                                '<span class="glyphicon glyphicon-off"></span> Logout (' . Yii::$app->user->identity->usuario . ')', ['class' => 'btn btn-link logout']
                        )
                        . Html::endForm()
                        . '</li>'
                        )
                    ],
                ]);
                NavBar::end();
            }
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container" >
                <p class="pull-right">Jose María Cagigas Céspedes - Task Manager 2018</p>
            </div>
        </footer>
        <?php
        echo app\widgets\Modal::widget([
            "boton" => "modalLogin"
        ]);
        ?>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>