models/User.php
<?php

namespace app\models;

use Yii;

class User extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface {

    public $password_repeat;
    public $codigo;
    

    public static function tableName() {
        return 'usuarios';
    }

    public function rules() {
        return [
            [['usuario', 'password'], 'string', 'max' => 255],
            [['usuario', 'password', 'password_repeat'], 'required', 'message' => 'El campo {attribute} es obligatorio'],
            // que el usuario no exista
            ['usuario', 'unique', 'message' => 'El usuario ya existe en el sistema'],
            ['password', 'string', 'min' => 4, 'message' => 'la contraseña debe tener al menos 6 caracteres'],
            //comparacion de contraseñas
            ['password_repeat', 'compare', 'compareAttribute' => 'password', 'operator' => '==', 'message' => 'Las contraseñas deben coincidir'],
            // validacion de captcha
            //['codigo', 'captcha', 'message' => 'No coincide el codigo mostrado'], // esto funcionaria correctamente sin AJAX
            //Con AJAX existe un bug lo corregimos con una funcion
            ['codigo', 'codeVerify'],
            [['email'], 'string', 'max' => 50],
            ['codigo', 'required', 'message' => 'Debes escribir algo en los codigos'],
            //colocar los campos que necesito que pase en la asignacion masiva
            [['password_repeat', 'password', 'usuario', 'codigo'], 'safe'],
            [['active'], 'integer'],
        ];
    }

    public function attributeLabels() {
        return [
            'id' => 'ID',
            'usuario' => 'Username',
            'password' => 'Password',
            'password_repeat' => 'Repeat password',
            'email' => 'Email',
            'active' => 'Active',
            'codigo' => 'Write the codes you see'
        ];
    }

    public function codeVerify($attribute) {
        /* nombre de la accion del controlador */
        $captcha_validate = new \yii\captcha\CaptchaAction('captcha', Yii::$app->controller);


        if ($this->$attribute) {
            $code = $captcha_validate->getVerifyCode();
            if ($this->$attribute != $code) {
                $this->addError($attribute, 'That verification code is not correct');
            }
        }
    }

    public static function findIdentity($id) {
        return static::findOne(['id' => $id]);
    }

    public static function findByUsername($username) {
        return static::findOne(['usuario' => $username]);
    }

    /**
     * @inheritdoc
     */
    public function getId() {
        return $this->getPrimaryKey();
    }

    /* public function validatePassword($password)
      {
      return Yii::$app->security->validatePassword($password, $this->password_hash);
      } */

//    public function validatePassword($password) {
//        return $this->password === $password;
//    }

    public function validatePassword($password) {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey() {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey) {
        return $this->getAuthKey() === $authKey;
    }

    public static function findIdentityByAccessToken($token, $type = null) {
        return null;
    }

    public function beforeSave($insert) {

        if (parent::beforeSave($insert)) {

            if ($this->isNewRecord) {

                $this->authKey = \Yii::$app->security->generateRandomString();
                $this->password = Yii::$app->security->generatePasswordHash($this->password);
            }

            return true;
        }

        return false;
    }

    public function afterSave($insert) {
        // entra solamente si es insercion y no actualizacion
        if ($insert) {
            $body = "<h1>Haga click en el siguiente enlace para finalizar tu registro</h1>";
            $body .= "<a href='" . Yii::$app->params["direccion"] . Yii::$app->request->baseUrl . "/index.php/front/confirm?id=" . urlencode($this->id) . "&authKey=" . urlencode($this->authKey) . "'>Confirmar</a>";
            Yii::$app->mailer->compose()
                    ->setTo($this->email)
                    ->setFrom([Yii::$app->params["adminEmail"] => Yii::$app->params["titulo"]])
                    ->setSubject("Terminar el registro")
                    ->setHtmlBody($body)
                    ->send();
        }
    }
}

controllers/BackController.php
<?php

/*
 * Controlador principal
 *
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use yii\widgets\ActiveForm;

class BackController extends Controller {

    // vamos a controlar las reglas de acceso
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [''],
                'rules' => [
                    [
                        'actions' => ['chores', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null, //con esto preguntamos que el entorno está en modo test
            ],
        ];
    }

    public function init() {
        parent::init();
        $this->layout = "backLayout";
    }

    public function entrar() {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        if (Yii::$app->user->identity->usuario != "admin") {
            return $this->goHome();
        }
    }

    public function actionIndex() {
        $this->entrar();
        return $this->render("index");
    }

    public function actionLogin() {
        // en caso de no estar logueado nos colocamos en la pagina de inicio

        if (!Yii::$app->user->isGuest) {
            return $this->redirect(["back/index"]);
        }

        $model = new LoginForm();
        // en caso de intentar realizar un logueo
        if ($model->load(Yii::$app->request->post()) && $model->admin()) {

            return $this->redirect(["back/index"]);
        }

        // en caso de que el logueo no sea correcto no entramos
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    public function actionLogout() {
        // nos salimos de la sesion
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /* accion para enviar un correo con formulario */

    public function actionContact($id) {
        $model = new ContactForm();
        $usuario=User::findIdentity($id);
        
        if ($model->load(Yii::$app->request->post()) && $model->contact()) {
            Yii::$app->session->setFlash('Email');
            //evitar envio masivo del correo con F5
            return $this->goHome();
        }
        
        $model->name=$usuario->usuario;
        $model->email=$usuario->email;
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }
    

    public function actionRegistrar() {
        $model = new User();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        /* crear el usuario */
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->refresh();
        }

        return $this->render('registro', [
                    'model' => $model,
        ]);
    }

    public function actionAjax() {
        $model = new User();

        /* validar por AJAX */
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        } else {
            return $this->renderAjax('registro', [
                        'model' => $model,
            ]);
        }
    }

    public function actionChema() {
        $this->redirect(['site/index']);
    }

    public function actionFormSubmission() {
        $security = new Security();
        $string = Yii::$app->request->post('string');
        $stringHash = '';
        if (!is_null($string)) {
            $stringHash = $security->generatePasswordHash($string);
        }
        return $this->render('form-submission', [
                    'stringHash' => $stringHash,
        ]);
    }

    public function actionAutoRefresh() {
        return $this->render('auto-refresh', ['time' => date('H:i:s')]);
    }

}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Usuarios;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller {

    /**
     * @inheritdoc
     */
    public function init() {
        parent::init();
        $this->layout = "backLayout";
    }

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Usuarios::find(),
        ]);

        $dataProvider->pagination->pageSize = 10;

        return $this->render('index', [
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'usuario')->textInput(['maxlength' => true, 'readonly' => true]) ?>

    <?= $form->field($model, 'email')->input('email', ['maxlength' => true, 'readonly' => true]) ?>

    <?= $form->field($model, 'active')->dropDownList(['0'=>'Disabled','1'=>'Activated']);  ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'User';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'usuario',
            'email:email',
            'active:boolean',
//            [
//                'label' => 'Active',
//                'value' => function($model) {
//                    return ($model->active === 1) ? 'Disabled' : 'Activated';
//                }
//            ],
            [
                'header' => 'View',
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}',
            ],
            [
                'header' => 'Update',
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}',
            ],
            [
                'header' => 'Delete',
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
            ], [
                'header' => 'Contact',
                'class' => 'yii\grid\ActionColumn',
                'template' => '{contact}',
                'buttons' => [
                    'contact' => function($url, $model) {
                        return Html::a('<span class="fa fa-envelope fa-2x"></span>', ['back/contact', 'id' => $model->id]);
                    },
                ],
            ],
        ],
    ]);
    ?>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Update Users:';
$this->params['breadcrumbs'][] = ['label' => 'User', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->usuario, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="chores-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'User', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?=
        Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ])
        ?>
    </p>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'usuario',
            'email:email',
            'active:boolean',
//            [
//                'label' => 'Active',
//                'value' => function($model) {
//                    return ($model->active === 1) ? 'Disabled' : 'Activated';
//                }
//            ],
        ],
    ])
    ?>

</div>