controllers/FrontController.php
<?php

/*
 * Controlador principal
 *
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\ContactForm;
use app\models\LoginForm;
use app\models\User;
use yii\widgets\ActiveForm;

class FrontController extends Controller {

    // vamos a controlar las reglas de acceso
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['contact'],
                'rules' => [
                    [
                        'actions' => ['contact', 'chores', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null, //con esto preguntamos que el entorno está en modo test
            ],
        ];
    }

    public function actionIndex() {
        $this->layout = "frontLayout";
        // cargamos la pagina de inicio
        return $this->render('index');
    }

    public function actionLogin($id = 0) {
        // en caso de no estar logueado nos colocamos en la pagina de inicio
        $this->layout = "frontLayout";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        // en caso de intentar realizar un logueo
        if ($id == 0) {
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                // si es correcto volvemos a la pagina anterior
                return $this->goBack();
            }

            // en caso de que el logueo no sea correcto no entramos
            return $this->renderPartial('login', [
                        'model' => $model,
            ]);
        } else {

            return $this->render('login', [
                        'model' => $model,
            ]);
        }
    }

    public function actionLogout() {
        // nos salimos de la sesion
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact() {
        $this->layout = "frontLayout";
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('Email');
            //evitar envio masivo del correo con F5
            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    public function actionRegistrar() {
        $this->layout = "frontLayout";
        $model = new User();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        /* crear el usuario */
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->goHome();
        }

        return $this->render('registro', [
                    'model' => $model,
        ]);
    }

    public function actionAjax() {
        $model = new User();

        /* validar por AJAX */
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        } else {
            return $this->renderAjax('registro', [
                        'model' => $model,
            ]);
        }
    }

    public function actionChema() {
        $this->redirect(['site/index']);
    }
    
    public function actionConfirm() {
        if (Yii::$app->request->get()) {

            //Obtenemos el valor de los parámetros get
            $id = \yii\helpers\Html::decode($_GET["id"]);
            $authKey = \yii\helpers\Html::decode($_GET["authKey"]);

            if ((int) $id) {
                //Realizamos la consulta para obtener el registro
                $model = User::find()
                        ->where("id=:id", [":id" => $id])
                        ->andWhere("authKey=:authKey", [":authKey" => $authKey]);
                
                //Si el registro existe
                if ($model->count() == 1) {
                    $activar = User::findOne($id);
                    $activar->active = 1;
//                    $activar->scenario="actualizar";
                    
                    if ($activar->save(false)) {
                        echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; " . \yii\helpers\Url::to(["index"]) . "'>";
                    } else {
                        echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                        echo "<meta http-equiv='refresh' content='8; " . \yii\helpers\Url::to(["index"]) . "'>";
                    }
                } else { //Si no existe redireccionamos a login
                    return $this->redirect(["index"]);
                }
            } else { //Si id no es un número entero redireccionamos a login
                return $this->redirect(["index"]);
            }
        }
    }

}

views/front/contact.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('Email')) { ?>

        <div class="alert alert-success">

            We can get in touch with you as soon as possible
        </div>

    <?php } else { ?>

        <p>
            To contact us send us a form
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']);
                ?>

                 <?= $form->field($model, 'name')->textInput(['readOnly' => true, 'value' => Yii::$app->user->identity->usuario]) ?>

                <?= $form->field($model, 'email')->textInput(['readOnly' => true, 'value' => Yii::$app->user->identity->email]) ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?=
                $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'captchaAction' => ['/back/captcha'],
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    'imageOptions' => [
                        'id' => 'my-captcha-image'
                    ],
                    'options' => [
                        'placeholder' => 'Write the text'
                    ]
                ])
                ?>
                <div class="form-group">
                    <?php
                    echo Html::tag('div', 'Change the image', [
                        'id' => 'refresh-captcha',
                        'class' => 'btn btn-info btn-xs'
                    ]);
                    ?>
                    <?php $this->registerJs("
            $('#refresh-captcha').on('click', function(e){
                e.preventDefault();
                $('#my-captcha-image').yiiCaptcha('refresh');
            })
        ");
                    ?>
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php } ?>
</div>

views/front/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/front/index.php
<?php

use app\components\Foto;

/* @var $this yii\web\View */
\app\assets\Animate::register($this);
$this->title = 'Task Manager 1.3';
?>
<div class="jumbotron">
    <span id="animationSandbox" style="display: block;" class="animated zoomIn">
    <h1 class="site_little mega">Task Manager</h1>
    </span>
    <div class="body-content">
    </div>
    <div class="row">
        <div class="col-md-12">
<?= Foto::widget(); ?>
        </div>
    </div>
</div>

views/front/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Enter in the system';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>


    <?php
    $form = ActiveForm::begin([
                'id' => 'login-form',
                'layout' => 'horizontal',
                'action' => ['front/login'],
                'fieldConfig' => [
                    'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                    'labelOptions' => ['class' => 'col-lg-1 control-label'],
                ],
    ]);
    ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?=
    $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])
    ?>
    <label>* - If you don't have a user account, you can create a new one here.</label>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-1">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
        <div class="col-lg-2">
            <?= Html::a('New User', ['front/registrar'], ['class' => 'btn btn-success pull-right', 'name' => 'new-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/front/mensaje.php
<h1>
<?= $model->nombre . " " . $model->apellidos ?>
</h1>
<div class="row"> 
El registro ha sido exitoso.
</div>

views/front/registro.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'New User';
$this->params['breadcrumbs'][] = ['label' => 'User', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="usuarios-create">

    <h1><?= Html::encode($this->title) ?></h1>


    <div class="usuarios-form">

        <?php
        $form = ActiveForm::begin([
                    'id' => $model->formName(),
                    'enableAjaxValidation' => true,
                        //'validationUrl' => ['site/ajax'],
        ]);

        /* vamos a colocar un alert con los mensajes de error del formulario */

        echo \yii\bootstrap\Alert::widget([
            'body' => $form->errorSummary($model, [
                'header' => 'The errors in the form are the following:'
            ]),
        ]);
        ?>

        <?= $form->field($model, 'usuario')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'password_repeat')->passwordInput(['maxlength' => true]); ?>

        <?= $form->field($model, 'active')->hiddenInput(['value' => 0])->label(false); ?>

        <?=
        $form->field($model, 'codigo')->widget(Captcha::className(), [
            'captchaAction' => ['/front/captcha'],
            'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
            'imageOptions' => [
                'id' => 'my-captcha-image'
            ],
            'options' => [
                'placeholder' => 'Write the text'
            ]
        ])
        ?>
        <div class="form-group">
            <?php
            echo Html::tag('div', 'Change the image', [
                'id' => 'refresh-captcha',
                'class' => 'btn btn-info btn-xs'
            ]);
            ?>
            <?php $this->registerJs("
            $('#refresh-captcha').on('click', function(e){
                e.preventDefault();
                $('#my-captcha-image').yiiCaptcha('refresh');
            })
        ");
            ?>
        </div>

        <div class="form-group">
            <?= Html::submitButton('Register', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>


</div>